import React, { useState, useEffect } from "react";
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine,
} from "recharts";

// Backtest results are loaded from public/backtest_summary.json
// Generated by: python agent/backtest.py
// Copy data/backtest_summary.json and data/equity_curve.csv to frontend/public/

export default function BacktestPage() {
  const [summary, setSummary]     = useState(null);
  const [equityCurve, setEquity]  = useState([]);
  const [loading, setLoading]     = useState(true);
  const [error, setError]         = useState(null);

  useEffect(() => {
    Promise.all([
      fetch("/backtest_summary.json").then((r) => r.json()).catch(() => null),
      fetch("/equity_curve.csv").then((r) => r.text()).catch(() => null),
    ]).then(([sum, csv]) => {
      setSummary(sum);
      if (csv) {
        const lines = csv.trim().split("\n").slice(1); // skip header
        const data  = lines.map((line) => {
          const [trade, cumPnl, equity] = line.split(",");
          return {
            trade:     parseInt(trade),
            cumPnlPct: parseFloat(cumPnl),
            equityIdx: parseFloat(equity),
          };
        });
        setEquity(data);
      }
      setLoading(false);
    }).catch((e) => {
      setError(e.message);
      setLoading(false);
    });
  }, []);

  if (loading) return <div className="page"><p>Loading backtest results...</p></div>;

  const hasData = summary && !summary.error;

  return (
    <div className="page">
      <h2>Backtest Results — BTC 7-Minute Momentum Signal</h2>

      <div className="notice info">
        <strong>Methodology:</strong> Tests the 7-minute BTC momentum hypothesis on closed
        Polymarket markets. At T+7 minutes, if BTC moved &gt;0.3% AND Polymarket odds were
        &lt;62% for that direction, the strategy would have entered. Results use Quarter-Kelly
        sizing and assume paper trading (no slippage modeled in v1).
        <br /><br />
        <strong>⚠️ Important limitation:</strong> This backtest approximates T+7 signals from
        market metadata. Tick-level backtesting with real order book data is a Phase 2
        improvement (see roadmap). Treat results as directional, not definitive.
      </div>

      {error && <div className="notice error">Failed to load data: {error}<br />
        Run <code>python agent/backtest.py</code> then copy results to <code>frontend/public/</code>
      </div>}

      {!hasData && !error && (
        <div className="notice warning">
          No backtest data found.<br />
          Run: <code>cd agent && python backtest.py</code><br />
          Then copy <code>data/backtest_summary.json</code> and <code>data/equity_curve.csv</code> to <code>frontend/public/</code>
        </div>
      )}

      {hasData && (
        <>
          {/* Summary stats */}
          <div className="stats-grid" style={{ marginBottom: "1.5rem" }}>
            <StatCard label="Total Trades"   value={summary.n_trades}          />
            <StatCard label="Win Rate"        value={`${summary.win_rate_pct}%`} alert={summary.win_rate_pct < 55} />
            <StatCard label="Avg Edge"        value={`${summary.avg_edge_pct}%`} />
            <StatCard label="Sharpe Ratio"    value={summary.sharpe_ratio}       alert={summary.sharpe_ratio < 0.8} />
            <StatCard label="Max Drawdown"    value={`${summary.max_drawdown_pct}%`} alert={summary.max_drawdown_pct < -20} />
            <StatCard label="Total P&L"       value={`${summary.total_pnl_pct > 0 ? "+" : ""}${summary.total_pnl_pct}%`} />
          </div>

          {/* Hypothesis verdict */}
          <div className={`notice ${summary.win_rate_pct >= 58 ? "success" : summary.win_rate_pct >= 52 ? "warning" : "error"}`}>
            {summary.win_rate_pct >= 58 && "✅ Win rate ≥58%: Hypothesis SUPPORTED — the 7-minute BTC momentum signal has measurable edge on historical data."}
            {summary.win_rate_pct >= 52 && summary.win_rate_pct < 58 && "🟡 Win rate 52–58%: Weak positive edge. More data or refined entry rules needed before live deployment."}
            {summary.win_rate_pct < 52 && "❌ Win rate <52%: Hypothesis NOT supported on this dataset. Signal rules need revision before live deployment."}
          </div>

          {/* Equity curve chart */}
          {equityCurve.length > 0 && (
            <div className="chart-section">
              <h3>Equity Curve (indexed to 100)</h3>
              <ResponsiveContainer width="100%" height={320}>
                <LineChart data={equityCurve} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#2a2a3a" />
                  <XAxis dataKey="trade" label={{ value: "Trade #", position: "insideBottom", offset: -3 }} tick={{ fill: "#aaa" }} />
                  <YAxis tick={{ fill: "#aaa" }} />
                  <Tooltip
                    contentStyle={{ background: "#1a1a2e", border: "1px solid #3a3a5e", color: "#eee" }}
                    formatter={(v, name) => [`${v.toFixed(2)}`, name === "equityIdx" ? "Equity Index" : "Cumulative P&L %"]}
                  />
                  <ReferenceLine y={100} stroke="#666" strokeDasharray="4 4" />
                  <Line type="monotone" dataKey="equityIdx" stroke="#7c5cfc" strokeWidth={2} dot={false} name="equityIdx" />
                </LineChart>
              </ResponsiveContainer>
              <p className="caption">
                Starting index = 100. Each trade uses Quarter-Kelly sizing (max 5% TVL).
              </p>
            </div>
          )}

          {/* Assumptions */}
          <div className="section">
            <h3>Explicit Assumptions (A1–A6)</h3>
            <table className="params-table">
              <tbody>
                <tr><td>A1</td><td>Favorite-longshot bias persists in BTC 15m markets</td><td>To be validated by this backtest</td></tr>
                <tr><td>A2</td><td>BTC 7-min momentum &gt;0.3% provides ≥8% edge</td><td><strong>HYPOTHESIS</strong> — validated by result above</td></tr>
                <tr><td>A3</td><td>Quarter-Kelly (25% of full Kelly) used for safety</td><td>Standard institutional practice (Kelly 1956)</td></tr>
                <tr><td>A4</td><td>All v1 trading is testnet only; no real funds</td><td>Explicit prototype scope</td></tr>
                <tr><td>A5</td><td>Tick-level T+7 data not available; metadata used as proxy</td><td>Phase 2 improvement: marketlens-python L2 data</td></tr>
                <tr><td>A6</td><td>No slippage modeled in v1 backtest</td><td>Conservative real edge = backtest edge − est. 1–2% slippage</td></tr>
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
}

function StatCard({ label, value, alert }) {
  return (
    <div className={`stat-card ${alert ? "stat-alert" : ""}`}>
      <div className="stat-label">{label}</div>
      <div className="stat-value">{value}</div>
    </div>
  );
}
